easy_admin:
    entities:
      Employee:
        class: App\Entity\Employee
        list:          
            title: "Сотрудники"
            pagination:
                - {name: 'next', label: 'Вперед'}
            actions:
                - { name: 'edit', icon: 'pencil', label: 'Изменить', css_class: 'btn btn-primary'}
                - { name: 'delete', icon: 'trash', label: 'Удалить', css_class: 'btn btn-danger'}
                - { name: 'new', icon: 'plus', label: 'Добавить', css_class: 'btn btn-succes'}
                - { name: 'search', label: 'Поиск'}
        edit:
            title: "Изменить данные сотрудника"
            actions:
#                - { name: 'save', label: 'Сохранить', css_class: 'btn btn-succes'}
                - { name: 'list', icon: 'remove', label: 'Отмена', css_class: 'btn btn-warning'}
                - { name: 'delete', icon: 'trash', label: 'Удалить', css_class: 'btn btn-danger'}
        modal:
            actions:
                - { name: 'cancel', icon: 'plus', label: 'Добавить', css_class: 'btn btn-succes'}
        form:
            fields:
              - {property: 'fio'}
              - {property: 'bdate'}
              - {property: 'photo'}
            