easy_admin:
    entities:
      Employee:
        class: App\Entity\Employee
        list:          
            title: "Сотрудники"
            pagination:
                - {name: 'next', label: 'Вперед'}
            actions:
                - { name: 'edit', icon: 'pencil', label: 'Изменить', css_class: 'btn btn-primary'}
                - { name: 'delete', icon: 'trash', label: 'Удалить', css_class: 'btn btn-danger'}
                - { name: 'new', icon: 'plus', label: 'Добавить', css_class: 'btn btn-succes'}
                - { name: 'search', label: 'Поиск'}
            fields:
                 - {property: 'id'}
                 - {property: 'fio', label: 'Ф.И.О'}
                 - {property: 'bdate', label: 'Дата рождения'}
                 - { property: 'image', type: 'image', base_path: '%app.path.product_images%', label: 'Фото' }
        edit:
            title: "Изменить данные сотрудника"
            actions:
#                - { name: 'save', label: 'Сохранить', css_class: 'btn btn-succes'}
                - { name: 'list', icon: 'remove', label: 'Отмена', css_class: 'btn btn-warning'}
                - { name: 'delete', icon: 'trash', label: 'Удалить', css_class: 'btn btn-danger'}
        modal:
            actions:
                - { name: 'cancel', icon: 'plus', label: 'Добавить', css_class: 'btn btn-succes'}
        form:
            title: "Добавить сотрудника"
            fields:
              - {property: 'fio', label: 'Ф.И.О'}
              - {property: 'bdate', default: '0000-00-00', type: 'birthday', label: 'Дата рождения'}
              - {property: 'imageFile', type: 'file', label: 'Фото'}
            
            # ...
        show:
           fields:
               - {property: 'fio', label: 'Ф.И.О'}
               - {property: 'bdate', label: 'Дата рождения', default: '0000-00-00'}
               - { property: 'image', type: 'image', base_path: '%app.path.product_images%', label: 'Фото' }

            