easy_admin:
    entities:
      Subdivision:
        class: App\Entity\Subdivision
        list:
            fields:   
                - {property: 'id'}
                - {property: 'title', label: 'Наименование'}
                - {property: 'address', label: 'Адрес'}
                - {property: 'director', label: 'Директор'}
           
            paginator:
                 - {name: 'next', label: 'Вперед'}
                    
            title: "Подразделения"
            actions:
                - { name: 'edit', icon: 'pencil', label: 'Изменить', css_class: 'btn btn-primary'}
                - { name: 'delete', icon: 'trash', label: 'Удалить', css_class: 'btn btn-danger'}
                - { name: 'new', icon: 'plus', label: 'Добавить', css_class: 'btn btn-succes'}
                - { name: 'search', label: 'Поиск'}
        edit:
            title: "Изменить данные подразделение"
            actions:
#                - { name: 'save', label: 'Сохранить', css_class: 'btn btn-succes'}
                - { name: 'list', icon: 'remove', label: 'Отмена', css_class: 'btn btn-warning'}
                - { name: 'delete', icon: 'trash', label: 'Удалить', css_class: 'btn btn-danger'}          
        form:
            title: "Добавить подразделение"
            fields:   
                - {property: 'title', label: 'Наименование'}
                - {property: 'address', label: 'Адрес'}
                - {property: 'director', label: 'Директор'}
           
                    
